#!/bin/sh
set -ex
cd "$(dirname "$0")/../../.."

tmp_dir=/tmp/php-src-download-bundled/timelib
rm -rf "$tmp_dir"

revision=refs/tags/2022.16

git clone --depth 1 --revision="$revision" https://github.com/derickr/timelib.git "$tmp_dir"

rm -rf ext/date/lib
cp -R "$tmp_dir" ext/date/lib

cd ext/date/lib

# clone timezonedb.h versioned independently
git fetch origin master
git restore -s f89fd25403f4e5e4c7548af39b3b0676c60b3793 -- timezonedb.h

# remove unneeded files
rm -r docs
rm -r tests
rm -r zones
rm gettzmapping.php
rm parse_zoneinfo.c
rm win_dirent.h

# patch customized files
rm -r .git
git apply -v ../../../.github/scripts/download-bundled/timelib.parse_date.patch
# generated by: git diff 529b145511^..529b145511 -- parse_date.re parse_iso_intervals.re timelib.c
git apply -v ../../../.github/scripts/download-bundled/timelib.GHSA-m8rr-4c36-8gq4.patch
