name: Push
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
permissions:
  contents: read
jobs:
  LINUX_X64:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:focal
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: apt
        uses: ./.github/actions/apt-x64
      - name: Setup
        uses: ./.github/actions/setup-x64
