name: Push
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
permissions:
  contents: read
env:
  CC: ccache gcc
  CXX: ccache g++
jobs:
  BENCHMARKING:
    name: BENCHMARKING
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: apt
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install \
            bison \
            libonig-dev \
            libsqlite3-dev \
            openssl \
            re2c \
            valgrind
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: "${{github.job}}-${{hashFiles('main/php_version.h')}}"
          append-timestamp: false
      - name: ./configure
        run: |
          set -x
          ./buildconf --force
          ./configure \
            --disable-debug \
            --enable-mbstring \
            --enable-opcache \
            --enable-option-checking=fatal \
            --enable-sockets \
            --enable-werror \
            --prefix=/usr \
            --with-config-file-scan-dir=/etc/php.d \
            --with-mysqli=mysqlnd \
            --with-openssl \
            --with-pdo-sqlite \
            --with-valgrind
      - name: make
        run: make -j$(/usr/bin/nproc) >/dev/null
      - name: make install
        run: |
          set -x
          sudo make install
          sudo mkdir -p /etc/php.d
          sudo chmod 777 /etc/php.d
          echo mysqli.default_socket=/var/run/mysqld/mysqld.sock > /etc/php.d/mysqli.ini
          echo zend_extension=opcache.so >> /etc/php.d/opcache.ini
          echo opcache.enable=1 >> /etc/php.d/opcache.ini
          echo opcache.enable_cli=1 >> /etc/php.d/opcache.ini
      - name: Setup
        run: |
          git config --global user.name "Benchmark"
          git config --global user.email "benchmark@php.net"
          sudo service mysql start
          mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS wordpress"
          mysql -uroot -proot -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY 'wordpress'; FLUSH PRIVILEGES;"
          mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'wordpress'@'localhost' WITH GRANT OPTION;"
      - name: git checkout benchmarking-data
        uses: actions/checkout@v4
        with:
          repository: php/benchmarking-data
          ssh-key: ${{ secrets.BENCHMARKING_DATA_DEPLOY_KEY }}
          path: benchmark/repos/data
      - name: Benchmark
        run: php benchmark/benchmark.php true
      - name: Show diff
        run: |-
          set -x
          php benchmark/generate_diff.php \
            ${{ github.sha }} \
            d463d215e185c802883e7940f9b7ae5034dd1e19 \
            > $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v4
        with:
          name: profiles
          path: ${{ github.workspace }}/benchmark/profiles
          retention-days: 30
