name: Setup
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x

        service slapd start

        locale-gen de_DE

        ps aux
        service slapd restart

        ./.github/scripts/setup-slapd.sh
