name: Setup
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x

        service slapd start

        locale-gen de_DE

        # fix slapd restarting
        # https://stackoverflow.com/questions/30671693/within-a-docker-image-slapd-stop-succeeds-but-slapd-is-still-running
        sed -i 's/--exec $SLAPD 2/--name slapd 2/' /etc/init.d/slapd

        cat /etc/init.d/slapd
        ls -lah /var/run/slapd/slapd.pid

        ps aux
        start-stop-daemon --stop --oknodo --retry TERM/10 --pidfile /var/run/slapd/slapd.pid --name slapd

        ps aux
        service slapd restart
        ps aux

        ./.github/scripts/setup-slapd.sh
