name: Setup
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x

        sudo service slapd start

        sudo locale-gen de_DE

        ./.github/scripts/setup-slapd.sh &>/dev/null
